package mail

var subjectStandard = []string{
	"Woof, Woof!",
	"Daily Pupdate",
	"Pupdate",
}
var subjectPuns = []string{
	"Who's ready to paw-ty?",
	"Howl you doin'?",
	"Who's ready fur some puppies?",
	"Why did the dog go to the bank? To make a de-paws-it.",
	"Who is the greatest dog detective that ever lived? Sherlock Bones.",
	"What was the sale this week at the pet store? Buy one dog, get one flea!",
	"Why was the puppy party so loud? They turned up the sub-woof-ers!",
	"Have you heard about the new dog movie? It’s called Jurassic Bark.",
	`What’s your dog’s favorite Pink Floyd album? "The Bark Side of the Moon."`,
	`What did the dog say to his shy friend? "You never stand up for yourself! You just roll over!"`,
	`What kind of car does a dog drive? A Fur-rari.`,
	`What's a dog's favorite movie? Harry Paw-ter and the Sorcerer's Bone!`,
	"I forgot to feed my dog on time and he hounded me about it all day.",
	"The Dalmatian hid from people because he didn’t want to be spotted.",
	`My dog’s not fat. He’s just a little Husky.`,
	`Don’t stop retrieving, hold on to that feline!`,
	`What dog does Dracula own? A Bloodhound.`,
	`Mistakes happen. There's no need to terrier self up about it.`,
	`My dog’s favorite band is The Beagles.`,
	`I'll Collie you later!`,
	`The Dachshund had to sit in the shade because it was a hot dog.`,
	`Be careful when it's raining cats and dogs. If you aren't, you could step in a Poodle.`,
	`You have the corg-key to my heart.`,
	`The newest Avenger is Labro-thor.`,
	`He’s Great Dane-gerous.`,
	`I need a cup of Earl Greyhound tea every day.`,
	`When a problem comes your way, you must Whippet.`,
}
